name: github pages

on:
  push:
    branches:
    - wip/gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install -g pnpm
    - run: pnpm install

    - run: pnpm run build:gh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_PERSONAL_TOKEN }}
        publish_dir: ./build
        keep_files: true
        publish_branch: wip/gh-pages  # default: gh-pages
        # deploy_key: ${{ secrets.ACTIONS_PERSONAL_TOKEN }}
        # external_repository: username/external-repository
      env:
        ACTIONS_PERSONAL_TOKEN: ${{ secrets.ACTIONS_PERSONAL_TOKEN }}
        PUBLISH_BRANCH: wip/gh-pages
        PUBLISH_DIR: ./build
